age2_L<- read.csv('/data/chamal/projects/saashi/ASD_heterogeneity/analysis/Rstats_new_Apr26-17/MERGE_CSVS_FDR/p_vals_header/meta_analysis_left_thickness_age_2-DX_p.csv')
age2_R<- read.csv('/data/chamal/projects/saashi/ASD_heterogeneity/analysis/Rstats_new_Apr26-17/MERGE_CSVS_FDR/p_vals_header/meta_analysis_right_thickness_age_2-DX_p.csv')
age4_L<- read.csv('/data/chamal/projects/saashi/ASD_heterogeneity/analysis/Rstats_new_Apr26-17/MERGE_CSVS_FDR/p_vals_header/meta_analysis_left_thickness_age_4-DX_p.csv')
age4_R<- read.csv('/data/chamal/projects/saashi/ASD_heterogeneity/analysis/Rstats_new_Apr26-17/MERGE_CSVS_FDR/p_vals_header/meta_analysis_right_thickness_age_4-DX_p.csv')
age6_L<- read.csv('/data/chamal/projects/saashi/ASD_heterogeneity/analysis/Rstats_new_Apr26-17/MERGE_CSVS_FDR/p_vals_header/meta_analysis_left_thickness_age_6-DX_p.csv')
age6_R<- read.csv('/data/chamal/projects/saashi/ASD_heterogeneity/analysis/Rstats_new_Apr26-17/MERGE_CSVS_FDR/p_vals_header/meta_analysis_right_thickness_age_6-DX_p.csv')
age8_L<- read.csv('/data/chamal/projects/saashi/ASD_heterogeneity/analysis/Rstats_new_Apr26-17/MERGE_CSVS_FDR/p_vals_header/meta_analysis_left_thickness_age_8-DX_p.csv')
age8_R<- read.csv('/data/chamal/projects/saashi/ASD_heterogeneity/analysis/Rstats_new_Apr26-17/MERGE_CSVS_FDR/p_vals_header/meta_analysis_right_thickness_age_8-DX_p.csv')
age10_L<- read.csv('/data/chamal/projects/saashi/ASD_heterogeneity/analysis/Rstats_new_Apr26-17/MERGE_CSVS_FDR/p_vals_header/meta_analysis_left_thickness_age_10-DX_p.csv')
age10_R<- read.csv('/data/chamal/projects/saashi/ASD_heterogeneity/analysis/Rstats_new_Apr26-17/MERGE_CSVS_FDR/p_vals_header/meta_analysis_right_thickness_age_10-DX_p.csv')
age12_L<- read.csv('/data/chamal/projects/saashi/ASD_heterogeneity/analysis/Rstats_new_Apr26-17/MERGE_CSVS_FDR/p_vals_header/meta_analysis_left_thickness_age_12-DX_p.csv')
age12_R<- read.csv('/data/chamal/projects/saashi/ASD_heterogeneity/analysis/Rstats_new_Apr26-17/MERGE_CSVS_FDR/p_vals_header/meta_analysis_right_thickness_age_12-DX_p.csv')
age14_L<- read.csv('/data/chamal/projects/saashi/ASD_heterogeneity/analysis/Rstats_new_Apr26-17/MERGE_CSVS_FDR/p_vals_header/meta_analysis_left_thickness_age_14-DX_p.csv')
age14_R<- read.csv('/data/chamal/projects/saashi/ASD_heterogeneity/analysis/Rstats_new_Apr26-17/MERGE_CSVS_FDR/p_vals_header/meta_analysis_right_thickness_age_14-DX_p.csv')
age16_L<- read.csv('/data/chamal/projects/saashi/ASD_heterogeneity/analysis/Rstats_new_Apr26-17/MERGE_CSVS_FDR/p_vals_header/meta_analysis_left_thickness_age_16-DX_p.csv')
age16_R<- read.csv('/data/chamal/projects/saashi/ASD_heterogeneity/analysis/Rstats_new_Apr26-17/MERGE_CSVS_FDR/p_vals_header/meta_analysis_right_thickness_age_16-DX_p.csv')
age18_L<- read.csv('/data/chamal/projects/saashi/ASD_heterogeneity/analysis/Rstats_new_Apr26-17/MERGE_CSVS_FDR/p_vals_header/meta_analysis_left_thickness_age_18-DX_p.csv')
age18_R<- read.csv('/data/chamal/projects/saashi/ASD_heterogeneity/analysis/Rstats_new_Apr26-17/MERGE_CSVS_FDR/p_vals_header/meta_analysis_right_thickness_age_18-DX_p.csv')
age20_L<- read.csv('/data/chamal/projects/saashi/ASD_heterogeneity/analysis/Rstats_new_Apr26-17/MERGE_CSVS_FDR/p_vals_header/meta_analysis_left_thickness_age_20-DX_p.csv')
age20_R<- read.csv('/data/chamal/projects/saashi/ASD_heterogeneity/analysis/Rstats_new_Apr26-17/MERGE_CSVS_FDR/p_vals_header/meta_analysis_right_thickness_age_20-DX_p.csv')
age22_L<- read.csv('/data/chamal/projects/saashi/ASD_heterogeneity/analysis/Rstats_new_Apr26-17/MERGE_CSVS_FDR/p_vals_header/meta_analysis_left_thickness_age_22-DX_p.csv')
age22_R<- read.csv('/data/chamal/projects/saashi/ASD_heterogeneity/analysis/Rstats_new_Apr26-17/MERGE_CSVS_FDR/p_vals_header/meta_analysis_right_thickness_age_22-DX_p.csv')
age24_L<- read.csv('/data/chamal/projects/saashi/ASD_heterogeneity/analysis/Rstats_new_Apr26-17/MERGE_CSVS_FDR/p_vals_header/meta_analysis_left_thickness_age_24-DX_p.csv')
age24_R<- read.csv('/data/chamal/projects/saashi/ASD_heterogeneity/analysis/Rstats_new_Apr26-17/MERGE_CSVS_FDR/p_vals_header/meta_analysis_right_thickness_age_24-DX_p.csv')
age26_L<- read.csv('/data/chamal/projects/saashi/ASD_heterogeneity/analysis/Rstats_new_Apr26-17/MERGE_CSVS_FDR/p_vals_header/age-added/meta_analysis_left_thickness_age_26-DX_p.csv')
age26_R<- read.csv('/data/chamal/projects/saashi/ASD_heterogeneity/analysis/Rstats_new_Apr26-17/MERGE_CSVS_FDR/p_vals_header/age-added/meta_analysis_right_thickness_age_26-DX_p.csv')
age28_L<- read.csv('/data/chamal/projects/saashi/ASD_heterogeneity/analysis/Rstats_new_Apr26-17/MERGE_CSVS_FDR/p_vals_header/age-added/meta_analysis_left_thickness_age_28-DX_p.csv')
age28_R<- read.csv('/data/chamal/projects/saashi/ASD_heterogeneity/analysis/Rstats_new_Apr26-17/MERGE_CSVS_FDR/p_vals_header/age-added/meta_analysis_right_thickness_age_28-DX_p.csv')
age30_L<- read.csv('/data/chamal/projects/saashi/ASD_heterogeneity/analysis/Rstats_new_Apr26-17/MERGE_CSVS_FDR/p_vals_header/age-added/meta_analysis_left_thickness_age_30-DX_p.csv')
age30_R<- read.csv('/data/chamal/projects/saashi/ASD_heterogeneity/analysis/Rstats_new_Apr26-17/MERGE_CSVS_FDR/p_vals_header/age-added/meta_analysis_right_thickness_age_30-DX_p.csv')
age32_L<- read.csv('/data/chamal/projects/saashi/ASD_heterogeneity/analysis/Rstats_new_Apr26-17/MERGE_CSVS_FDR/p_vals_header/age-added/meta_analysis_left_thickness_age_32-DX_p.csv')
age32_R<- read.csv('/data/chamal/projects/saashi/ASD_heterogeneity/analysis/Rstats_new_Apr26-17/MERGE_CSVS_FDR/p_vals_header/age-added/meta_analysis_right_thickness_age_32-DX_p.csv')
FIQ80_L<- read.csv('/data/chamal/projects/saashi/ASD_heterogeneity/analysis/Rstats_new_Apr26-17/MERGE_CSVS_FDR/p_vals_header/FIQ_nimh/meta_analysis_left_thickness_DX-FIQ_80_p.csv')
FIQ80_R<- read.csv('/data/chamal/projects/saashi/ASD_heterogeneity/analysis/Rstats_new_Apr26-17/MERGE_CSVS_FDR/p_vals_header/FIQ_nimh/meta_analysis_right_thickness_DX-FIQ_80_p.csv')
FIQ90_L<- read.csv('/data/chamal/projects/saashi/ASD_heterogeneity/analysis/Rstats_new_Apr26-17/MERGE_CSVS_FDR/p_vals_header/FIQ_nimh/meta_analysis_left_thickness_DX-FIQ_90_p.csv')
FIQ90_R<- read.csv('/data/chamal/projects/saashi/ASD_heterogeneity/analysis/Rstats_new_Apr26-17/MERGE_CSVS_FDR/p_vals_header/FIQ_nimh/meta_analysis_right_thickness_DX-FIQ_90_p.csv')
FIQ100_L<- read.csv('/data/chamal/projects/saashi/ASD_heterogeneity/analysis/Rstats_new_Apr26-17/MERGE_CSVS_FDR/p_vals_header/FIQ_nimh/meta_analysis_left_thickness_DX-FIQ_100_p.csv')
FIQ100_R<- read.csv('/data/chamal/projects/saashi/ASD_heterogeneity/analysis/Rstats_new_Apr26-17/MERGE_CSVS_FDR/p_vals_header/FIQ_nimh/meta_analysis_right_thickness_DX-FIQ_100_p.csv')
FIQ110_L<- read.csv('/data/chamal/projects/saashi/ASD_heterogeneity/analysis/Rstats_new_Apr26-17/MERGE_CSVS_FDR/p_vals_header/FIQ_nimh/meta_analysis_left_thickness_DX-FIQ_110_p.csv')
FIQ110_R<- read.csv('/data/chamal/projects/saashi/ASD_heterogeneity/analysis/Rstats_new_Apr26-17/MERGE_CSVS_FDR/p_vals_header/FIQ_nimh/meta_analysis_right_thickness_DX-FIQ_110_p.csv')
FIQ120_L<- read.csv('/data/chamal/projects/saashi/ASD_heterogeneity/analysis/Rstats_new_Apr26-17/MERGE_CSVS_FDR/p_vals_header/FIQ_nimh/meta_analysis_left_thickness_DX-FIQ_120_p.csv')
FIQ120_R<- read.csv('/data/chamal/projects/saashi/ASD_heterogeneity/analysis/Rstats_new_Apr26-17/MERGE_CSVS_FDR/p_vals_header/FIQ_nimh/meta_analysis_right_thickness_DX-FIQ_120_p.csv')
FIQ130_L<- read.csv('/data/chamal/projects/saashi/ASD_heterogeneity/analysis/Rstats_new_Apr26-17/MERGE_CSVS_FDR/p_vals_header/FIQ_nimh/meta_analysis_left_thickness_DX-FIQ_130_p.csv')
FIQ130_R<- read.csv('/data/chamal/projects/saashi/ASD_heterogeneity/analysis/Rstats_new_Apr26-17/MERGE_CSVS_FDR/p_vals_header/FIQ_nimh/meta_analysis_right_thickness_DX-FIQ_130_p.csv')
FIQ140_L<- read.csv('/data/chamal/projects/saashi/ASD_heterogeneity/analysis/Rstats_new_Apr26-17/MERGE_CSVS_FDR/p_vals_header/FIQ_nimh/meta_analysis_left_thickness_DX-FIQ_140_p.csv')
FIQ140_R<- read.csv('/data/chamal/projects/saashi/ASD_heterogeneity/analysis/Rstats_new_Apr26-17/MERGE_CSVS_FDR/p_vals_header/FIQ_nimh/meta_analysis_right_thickness_DX-FIQ_140_p.csv')
DX_L<- read.csv('/data/chamal/projects/saashi/ASD_heterogeneity/analysis/Rstats_new_Apr26-17/MERGE_CSVS_FDR/p_vals_header/meta_analysis_left_thickness_DX_June29_p.csv')
DX_R<- read.csv('/data/chamal/projects/saashi/ASD_heterogeneity/analysis/Rstats_new_Apr26-17/MERGE_CSVS_FDR/p_vals_header/meta_analysis_right_thickness_DX_June29_p.csv')
M_DX_L<- read.csv('/data/chamal/projects/saashi/ASD_heterogeneity/analysis/Rstats_new_Apr26-17/MERGE_CSVS_FDR/p_vals_header/meta_analysis_left_thickness_DX_M_p.csv')
M_DX_R<- read.csv('/data/chamal/projects/saashi/ASD_heterogeneity/analysis/Rstats_new_Apr26-17/MERGE_CSVS_FDR/p_vals_header/meta_analysis_right_thickness_DX_M_p.csv')
F_DX_L<- read.csv('/data/chamal/projects/saashi/ASD_heterogeneity/analysis/Rstats_new_Apr26-17/MERGE_CSVS_FDR/p_vals_header/meta_analysis_left_thickness_DX_F_p.csv')
F_DX_R<- read.csv('/data/chamal/projects/saashi/ASD_heterogeneity/analysis/Rstats_new_Apr26-17/MERGE_CSVS_FDR/p_vals_header/meta_analysis_right_thickness_DX_F_p.csv')
CSS_L<-read.csv('/data/chamal/projects/saashi/ASD_heterogeneity/analysis/Rstats_new_Apr26-17/MERGE_CSVS_FDR/p_vals_header/age-FIQ_2-3_CSS/meta_analysis_left_thickness_Severity_ADOS_2_SEV_UNCORRECTED_p.csv')
CSS_R<-read.csv('/data/chamal/projects/saashi/ASD_heterogeneity/analysis/Rstats_new_Apr26-17/MERGE_CSVS_FDR/p_vals_header/age-FIQ_2-3_CSS/meta_analysis_right_thickness_Severity_ADOS_2_SEV_UNCORRECTED_p.csv')
RRB_L<-read.csv('/data/chamal/projects/saashi/ASD_heterogeneity/analysis/Rstats_new_Apr26-17/MERGE_CSVS_FDR/p_vals_header/severity_added/ADOS2/meta_analysis_left_thickness_RRB_ADOS_2_3_UNCORRECTED_p.csv') 
RRB_R<-read.csv('//data/chamal/projects/saashi/ASD_heterogeneity/analysis/Rstats_new_Apr26-17/MERGE_CSVS_FDR/p_vals_header/severity_added/ADOS2/meta_analysis_right_thickness_RRB_ADOS_2_3_UNCORRECTED_p.csv') 
SOC_L<-read.csv('/data/chamal/projects/saashi/ASD_heterogeneity/analysis/Rstats_new_Apr26-17/MERGE_CSVS_FDR/p_vals_header/severity_added/ADOS2/meta_analysis_left_thickness_SOC_ADOS_2_3_UNCORRECTED_p.csv') 
SOC_R<-read.csv('/data/chamal/projects/saashi/ASD_heterogeneity/analysis/Rstats_new_Apr26-17/MERGE_CSVS_FDR/p_vals_header/severity_added/ADOS2/meta_analysis_right_thickness_SOC_ADOS_2_3_UNCORRECTED_p.csv')
AQ_L<-read.csv('/data/chamal/projects/saashi/ASD_heterogeneity/analysis/Rstats_new_Apr26-17/MERGE_CSVS_FDR/p_vals_header/severity_added/meta_analysis_left_thickness_AQ-DX_interac_UNCORRECTED_p.csv')
AQ_R<-read.csv('/data/chamal/projects/saashi/ASD_heterogeneity/analysis/Rstats_new_Apr26-17/MERGE_CSVS_FDR/p_vals_header/severity_added/meta_analysis_right_thickness_AQ-DX_interac_UNCORRECTED_p.csv')
SRS_L<-read.csv('/data/chamal/projects/saashi/ASD_heterogeneity/analysis/Rstats_new_Apr26-17/MERGE_CSVS_FDR/p_vals_header/severity_added/meta_analysis_left_thickness_SRS-DX_interac_UNCORRECTED_p.csv')
SRS_R<-read.csv('/data/chamal/projects/saashi/ASD_heterogeneity/analysis/Rstats_new_Apr26-17/MERGE_CSVS_FDR/p_vals_header/severity_added/meta_analysis_right_thickness_SRS-DX_interac_UNCORRECTED_p.csv')
CSS_sex_L<-read.csv('/data/chamal/projects/saashi/ASD_heterogeneity/analysis/Rstats_new_Apr26-17/MERGE_CSVS_FDR/p_vals_header/severity_added/meta_analysis_left_thickness_Severity_ADOS_2_sev_interac_UNCORRECTED_p.csv')
CSS_sex_R<-read.csv('/data/chamal/projects/saashi/ASD_heterogeneity/analysis/Rstats_new_Apr26-17/MERGE_CSVS_FDR/p_vals_header/severity_added/meta_analysis_right_thickness_Severity_ADOS_2_sev_interac_UNCORRECTED_p.csv')
CSS_F_L<-read.csv('/data/chamal/projects/saashi/ASD_heterogeneity/analysis/Rstats_new_Apr26-17/MERGE_CSVS_FDR/p_vals_header/severity_added/meta_analysis_left_thickness_Severity_ADOS_2_sev_F_UNCORRECTED_p.csv')
CSS_F_R<-read.csv('/data/chamal/projects/saashi/ASD_heterogeneity/analysis/Rstats_new_Apr26-17/MERGE_CSVS_FDR/p_vals_header/severity_added/meta_analysis_right_thickness_Severity_ADOS_2_sev_F_UNCORRECTED_p.csv')
CSS_M_L<-read.csv('/data/chamal/projects/saashi/ASD_heterogeneity/analysis/Rstats_new_Apr26-17/MERGE_CSVS_FDR/p_vals_header/severity_added/meta_analysis_left_thickness_Severity_ADOS_2_sev_M_UNCORRECTED_p.csv')
CSS_M_R<-read.csv('/data/chamal/projects/saashi/ASD_heterogeneity/analysis/Rstats_new_Apr26-17/MERGE_CSVS_FDR/p_vals_header/severity_added/meta_analysis_right_thickness_Severity_ADOS_2_sev_M_UNCORRECTED_p.csv')
RRB_G_L<-read.csv('/data/chamal/projects/saashi/ASD_heterogeneity/analysis/Rstats_new_Apr26-17/MERGE_CSVS_FDR/p_vals_header/severity_added/ADOS_G/meta_analysis_left_thickness_RRB_ADOS_G_4_UNCORRECTED_p.csv')
RRB_G_R<-read.csv('/data/chamal/projects/saashi/ASD_heterogeneity/analysis/Rstats_new_Apr26-17/MERGE_CSVS_FDR/p_vals_header/severity_added/ADOS_G/meta_analysis_right_thickness_RRB_ADOS_G_4_UNCORRECTED_p.csv')
SOC_G_L<-read.csv('/data/chamal/projects/saashi/ASD_heterogeneity/analysis/Rstats_new_Apr26-17/MERGE_CSVS_FDR/p_vals_header/severity_added/ADOS_G/meta_analysis_left_thickness_SOC_ADOS_G_4_UNCORRECTED_p.csv')
SOC_G_R<-read.csv('/data/chamal/projects/saashi/ASD_heterogeneity/analysis/Rstats_new_Apr26-17/MERGE_CSVS_FDR/p_vals_header/severity_added/ADOS_G/meta_analysis_right_thickness_SOC_ADOS_G_4_UNCORRECTED_p.csv')
COM_G_L<-read.csv('/data/chamal/projects/saashi/ASD_heterogeneity/analysis/Rstats_new_Apr26-17/MERGE_CSVS_FDR/p_vals_header/severity_added/ADOS_G/meta_analysis_left_thickness_COMM_ADOS_G_4_UNCORRECTED_p.csv')
COM_G_R<-read.csv('/data/chamal/projects/saashi/ASD_heterogeneity/analysis/Rstats_new_Apr26-17/MERGE_CSVS_FDR/p_vals_header/severity_added/ADOS_G/meta_analysis_right_thickness_COMM_ADOS_G_4_UNCORRECTED_p.csv')


#rename column in DX (and M + F) and CSS 
names(DX_L) <- c("dx_p")
names(DX_R) <- c("dx_p")
names(M_DX_L) <- c("dx_p")
names(M_DX_R) <- c("dx_p")
names(F_DX_L) <- c("dx_p")
names(F_DX_R) <- c("dx_p")
names(CSS_L) <- c("dx_p")
names(CSS_R) <- c("dx_p")
names(RRB_L) <- c("dx_p")
names(RRB_R) <- c("dx_p")
names(SOC_L) <- c("dx_p")
names(SOC_R) <- c("dx_p")
names(AQ_L) <- c("dx_p")
names(AQ_R) <- c("dx_p")
names(SRS_L) <- c("dx_p")
names(SRS_R) <- c("dx_p")
names(CSS_sex_L) <- c("dx_p")
names(CSS_sex_R) <- c("dx_p")
names(CSS_F_L) <- c("dx_p")
names(CSS_F_R) <- c("dx_p")
names(CSS_M_L) <- c("dx_p")
names(CSS_M_R) <- c("dx_p")
names(RRB_G_L) <- c("dx_p")
names(RRB_G_R) <- c("dx_p")
names(SOC_G_L) <- c("dx_p")
names(SOC_G_R) <- c("dx_p")
names(COM_G_L) <- c("dx_p")
names(COM_G_R) <- c("dx_p")



all_p<- rbind(age2_L, age2_R, age4_L, age4_R, age6_L, age6_R, age8_L, age8_R, age10_L, age10_R, age12_L, age12_R, age14_L, age14_R, age16_L, age16_R, age18_L, age18_R, age20_L, age20_R, age22_L, age22_R, age24_L, age24_R, age26_L, age26_R, age28_L, age28_R, age30_L, age30_R, age32_L, age32_R, FIQ80_L, FIQ80_R, FIQ90_L, FIQ90_R, FIQ100_L, FIQ100_R, FIQ110_L, FIQ110_R, FIQ120_L, FIQ120_R, FIQ130_L, FIQ130_R, FIQ140_L, FIQ140_R, DX_L, DX_R, M_DX_L, M_DX_R, F_DX_L, F_DX_R, CSS_L, CSS_R, RRB_L, RRB_R, SOC_L, SOC_R, AQ_L, AQ_R, SRS_L, SRS_R, CSS_sex_L, CSS_sex_R, CSS_F_L, CSS_F_R, CSS_M_L, CSS_M_R, RRB_G_L, RRB_G_R, SOC_G_L, SOC_G_R, COM_G_L, COM_G_R)

write.table(all_p, file="all_p_vals.csv", sep=",", row.names=F)

all_p$dx_p_adjust <- p.adjust(all_p$dx_p, "fdr")
write.table(all_p, file="all_p_vals_FDR.csv", sep=",", row.names=F)

x<-all_p$dx_p_adjust


#loop to cut back into individual vertstats files - by 40962 .

#splits by sets of 40962 
data_list <- lapply(seq(from=1, to=3031188, by=40962), function(i) x[i:(i+40961)])

#names each one ie results_1; results_2; etc 
data_list <- setNames(data_list, paste0("results_", seq(length(data_list))))

#extracts all separated files from data_list
list2env(data_list, .GlobalEnv)

#write files. 
write.table(results_1, file="age2_L", sep=",", row.names=F)
write.table(results_2, file="age2_R", sep=",", row.names=F)
write.table(results_3, file="age4_L", sep=",", row.names=F)
write.table(results_4, file="age4_R", sep=",", row.names=F)
write.table(results_5, file="age6_L", sep=",", row.names=F)
write.table(results_6, file="age6_R", sep=",", row.names=F)
write.table(results_7, file="age8_L", sep=",", row.names=F)
write.table(results_8, file="age8_R", sep=",", row.names=F)
write.table(results_9, file="age10_L", sep=",", row.names=F)
write.table(results_10, file="age10_R", sep=",", row.names=F)
write.table(results_11, file="age12_L", sep=",", row.names=F)
write.table(results_12, file="age12_R", sep=",", row.names=F)
write.table(results_13, file="age14_L", sep=",", row.names=F)
write.table(results_14, file="age14_R", sep=",", row.names=F)
write.table(results_15, file="age16_L", sep=",", row.names=F)
write.table(results_16, file="age16_R", sep=",", row.names=F)
write.table(results_17, file="age18_L", sep=",", row.names=F)
write.table(results_18, file="age18_R", sep=",", row.names=F)
write.table(results_19, file="age20_L", sep=",", row.names=F)
write.table(results_20, file="age20_R", sep=",", row.names=F)
write.table(results_21, file="age22_L", sep=",", row.names=F)
write.table(results_22, file="age22_R", sep=",", row.names=F)
write.table(results_23, file="age24_L", sep=",", row.names=F)
write.table(results_24, file="age24_R", sep=",", row.names=F)
write.table(results_25, file="age26_L", sep=",", row.names=F)
write.table(results_26, file="age26_R", sep=",", row.names=F)
write.table(results_27, file="age28_L", sep=",", row.names=F)
write.table(results_28, file="age28_R", sep=",", row.names=F)
write.table(results_29, file="age30_L", sep=",", row.names=F)
write.table(results_30, file="age30_R", sep=",", row.names=F)
write.table(results_31, file="age32_L", sep=",", row.names=F)
write.table(results_32, file="age32_R", sep=",", row.names=F)
write.table(results_33, file="FIQ80_L", sep=",", row.names=F)
write.table(results_34, file="FIQ80_R", sep=",", row.names=F)
write.table(results_35, file="FIQ90_L", sep=",", row.names=F)
write.table(results_36, file="FIQ90_R", sep=",", row.names=F)
write.table(results_37, file="FIQ100_L", sep=",", row.names=F)
write.table(results_38, file="FIQ100_R", sep=",", row.names=F)
write.table(results_39, file="FIQ110_L", sep=",", row.names=F)
write.table(results_40, file="FIQ110_R", sep=",", row.names=F)
write.table(results_41, file="FIQ120_L", sep=",", row.names=F)
write.table(results_42, file="FIQ120_R", sep=",", row.names=F)
write.table(results_43, file="FIQ130_L", sep=",", row.names=F)
write.table(results_44, file="FIQ130_R", sep=",", row.names=F)
write.table(results_45, file="FIQ140_L", sep=",", row.names=F)
write.table(results_46, file="FIQ140_R", sep=",", row.names=F)
write.table(results_47, file="DX_L", sep=",", row.names=F)
write.table(results_48, file="DX_R", sep=",", row.names=F)
write.table(results_49, file="M_DX_L", sep=",", row.names=F)
write.table(results_50, file="M_DX_R", sep=",", row.names=F)
write.table(results_51, file="F_DX_L", sep=",", row.names=F)
write.table(results_52, file="F_DX_R", sep=",", row.names=F)
write.table(results_53, file="CSS_L", sep=",", row.names=F)
write.table(results_54, file="CSS_R", sep=",", row.names=F)
write.table(results_55, file="RRB_L", sep=",", row.names=F)
write.table(results_56, file="RRB_R", sep=",", row.names=F)
write.table(results_57, file="SOC_L", sep=",", row.names=F)
write.table(results_58, file="SOC_R", sep=",", row.names=F)
write.table(results_59, file="AQ_L", sep=",", row.names=F)
write.table(results_60, file="AQ_R", sep=",", row.names=F)
write.table(results_61, file="SRS_L", sep=",", row.names=F)
write.table(results_62, file="SRS_R", sep=",", row.names=F)
write.table(results_63, file="CSS_sex_L", sep=",", row.names=F)
write.table(results_64, file="CSS_sex_R", sep=",", row.names=F)
write.table(results_65, file="CSS_F_L", sep=",", row.names=F)
write.table(results_66, file="CSS_F_R", sep=",", row.names=F)
write.table(results_67, file="CSS_M_L", sep=",", row.names=F)
write.table(results_68, file="CSS_M_R", sep=",", row.names=F)
write.table(results_69, file="RRB_G_L", sep=",", row.names=F)
write.table(results_70, file="RRB_G_R", sep=",", row.names=F)
write.table(results_71, file="SOC_G_L", sep=",", row.names=F)
write.table(results_72, file="SOC_G_R", sep=",", row.names=F)
write.table(results_73, file="COM_G_L", sep=",", row.names=F)
write.table(results_74, file="COM_G_R", sep=",", row.names=F)

