

%spin test to assess spatial correspondence between cortical thickness map
%of statistical significance and boundary sharpness coefficient map.

% first step: generate null distribution of one of the maps (main effect BSC p
% values) by rotating it 100 times.

SpinPermuCIVET('/data/chamal/projects/emilyO/Tissue_contrast/analysis/spin-test/BSC_data/BSC_left_betas.csv','/data/chamal/projects/emilyO/Tissue_contrast/analysis/spin-test/BSC_data/BSC_right_betas.csv',500,'/data/chamal/projects/emilyO/Tissue_contrast/analysis/spin-test/null_BSC_500_combineFDR.mat')

%calcuate the p-value of correlation between two surface maps, based on the
%null distribution of spins generated by SpinPermuCIVET
pvalvsNull('/data/chamal/projects/emilyO/Tissue_contrast/analysis/spin-test/BSC_data/BSC_left_betas.csv','/data/chamal/projects/emilyO/Tissue_contrast/analysis/spin-test/BSC_data/BSC_left_betas.csv','/data/chamal/projects/emilyO/Tissue_contrast/analysis/spin-test/CT_data/left_CT_betas.csv','/data/chamal/projects/emilyO/Tissue_contrast/analysis/spin-test/CT_data/right_CT_betas.csv',500,'/data/chamal/projects/emilyO/Tissue_contrast/analysis/spin-test/null_BSC_500_combineFDR.mat')
load('/data/chamal/projects/emilyO/Tissue_contrast/analysis/cortical_gradient/meta-analysis/main_effect/unsmoothed/residualized/null_BSC.mat')

