% M and F BSC effect size maps spin test
%load M and F beta maps.
f_right=load('/Users/emilyolafson/Documents/BSC/spin-test/m_f/model_c_unsmoothed_sex_stratified_F_DX_right_beta_masked.txt');
f_left=load('/Users/emilyolafson/Documents/BSC/spin-test/m_f/model_c_unsmoothed_sex_stratified_F_DX_left_beta_masked.txt');
m_right=load('/Users/emilyolafson/Documents/BSC/spin-test/m_f/model_c_unsmoothed_sex_stratified_M_DX_right_beta_masked.txt');
m_left=load('/Users/emilyolafson/Documents/BSC/spin-test/m_f/model_c_unsmoothed_sex_stratified_M_DX_left_beta_masked.txt');

writematrix(f_right,'/Users/emilyolafson/Documents/BSC/spin-test/m_f/f_right.csv')
writematrix(f_left,'/Users/emilyolafson/Documents/BSC/spin-test/m_f/f_left.csv')
writematrix(m_right,'/Users/emilyolafson/Documents/BSC/spin-test/m_f/m_right.csv')
writematrix(m_left,'/Users/emilyolafson/Documents/BSC/spin-test/m_f/m_left.csv')

%spin test to assess spatial correspondence between cortical thickness map
%of statistical significance and boundary sharpness coefficient map.

% first step: generate null distribution of one of the maps (main effect BSC p
% values) by rotating it 100 times.

SpinPermuCIVET('/Users/emilyolafson/Documents/BSC/spin-test/m_f/f_left.csv','/Users/emilyolafson/Documents/BSC/spin-test/m_f/f_right.csv',500,'/Users/emilyolafson/Documents/BSC/spin-test/m_f/null_BSC_500_female2.mat')

%calcuate the p-value of correlation between two surface maps, based on the
%null distribution of spins generated by SpinPermuCIVET
pvalvsNull('/Users/emilyolafson/Documents/BSC/spin-test/m_f/f_right.csv','/Users/emilyolafson/Documents/BSC/spin-test/m_f/f_left.csv','/Users/emilyolafson/Documents/BSC/spin-test/m_f/m_right.csv','/Users/emilyolafson/Documents/BSC/spin-test/m_f/m_left.csv',500,'/Users/emilyolafson/Documents/BSC/spin-test/m_f/null_BSC_500_female2.mat')

null=load('m_f/nullrho_betas.txt')
real=load('m_f/realrho_betas.txt')
histogram(null, 75)
xline(real)
xline(real, 'r')
xline(real, 'r', 'LineWidth', 1)
xline(real, 'r', 'LineWidth', 3)
xlabel('Correlation')
xlabel('Pearson correlation coefficient')
ylabel('No. of permutations')
title('Null correlation histogram of overlap between M and F effect size maps from 500 permutations')
set(gca,'FontSize', 20)
xlabel('Pearson correlation coefficient')
text(0.15, 12, 'p = 0.122', 'FontSize', 20)


load('/data/chamal/projects/emilyO/Tissue_contrast/analysis/cortical_gradient/meta-analysis/main_effect/unsmoothed/residualized/null_BSC.mat')

