#across subject intensity curvature correlation.
library(RMINC)
library(ggplot2)

QCtable <- read.csv("/data/chamal/projects/emilyO/Tissue_contrast/raw_data/TORONTO/TO_demog.csv")
#exclude civet QC and motion fails
motionQC <- read.csv("/data/chamal/projects/emilyO/Tissue_contrast/spreadsheets/Total_MOTION_QC.csv")
civetQC <- read.csv("/data/chamal/projects/emilyO/Tissue_contrast/spreadsheets/Total_CIVET_QC.csv")
mask <- read.table('/opt/quarantine/resources/CIVET/CIVET-CC-mask.txt')
col_names <- c('Subject_ID', 'left_intensity','right_intensity', 'left_curvature', 'right_curvature')
row_names <- read.csv('/data/chamal/projects/emilyO/Tissue_contrast/raw_data/TORONTO/subjID.csv')
row_names_525 <- read.csv('/data/chamal/projects/emilyO/Tissue_contrast/raw_data/TORONTO/subjID_525.csv')
# extract voxelwise curvataure measure file locations
file.names.leftcurv <- dir('/data/chamal/projects/emilyO/Tissue_contrast/raw_data/mean_curvature/toronto', pattern ="_native_mc_rsl_28.28mm_white_left.txt", full.names = TRUE)
file.names.rightcurv <- dir('/data/chamal/projects/emilyO/Tissue_contrast/raw_data/mean_curvature/toronto', pattern ="_native_mc_rsl_28.28mm_white_right.txt", full.names = TRUE)
file.names.leftcurv <- cbind(row_names_525,file.names.leftcurv)
file.names.leftcurv <- merge(file.names.leftcurv, civetQC, by ="Subject_ID")
file.names.leftcurv <- merge(file.names.leftcurv, motionQC, by = "Subject_ID")
file.names.leftcurv <- subset(file.names.leftcurv,FINAL_MOTION_QC < 2)
file.names.leftcurv <- subset(file.names.leftcurv, FINAL_QC > 0)
file.names.rightcurv <- cbind(row_names_525,file.names.rightcurv)
file.names.rightcurv <- merge(file.names.rightcurv, civetQC, by ="Subject_ID")
file.names.rightcurv <- merge(file.names.rightcurv, motionQC, by = "Subject_ID")
file.names.rightcurv <- subset(file.names.rightcurv,FINAL_MOTION_QC < 2)
file.names.rightcurv <- subset(file.names.rightcurv, FINAL_QC > 0)

# extract voxelwise midsurface ratio ('int') measures file locations
file.names.leftint<- dir('/data/chamal/projects/emilyO/Tissue_contrast/analysis/cortical_gradient/final_pipeline_outputs/ratio/unsmoothed/toronto', pattern ="_model_ratio_left_20mm_rsl.txt", full.names = TRUE)
file.names.rightint <- dir('/data/chamal/projects/emilyO/Tissue_contrast/analysis/cortical_gradient/final_pipeline_outputs/ratio/unsmoothed/toronto', pattern ="_model_ratio_right_20mm_rsl.txt", full.names = TRUE)
file.names.leftint <- cbind(row_names_525,file.names.leftint)
file.names.leftint <- merge(file.names.leftint, civetQC, by ="Subject_ID")
file.names.leftint <- merge(file.names.leftint, motionQC, by = "Subject_ID")
file.names.leftint <- subset(file.names.leftint,FINAL_MOTION_QC < 2)
file.names.leftint <- subset(file.names.leftint, FINAL_QC > 0)
file.names.rightint <- cbind(row_names_525,file.names.rightint)
file.names.rightint <- merge(file.names.rightint, civetQC, by ="Subject_ID")
file.names.rightint <- merge(file.names.rightint, motionQC, by = "Subject_ID")
file.names.rightint <- subset(file.names.rightint,FINAL_MOTION_QC < 2)
file.names.rightint <- subset(file.names.rightint, FINAL_QC > 0)

# generate tables of subject (row) intensity (columns)
table.left_int <- vertexTable(as.character(file.names.leftint$file.names.leftint))
table.right_int <- vertexTable(as.character(file.names.rightint$file.names.rightint))
table.left_curv <- vertexTable(as.character(file.names.leftcurv$file.names.leftcurv))
table.right_curv <- vertexTable(as.character(file.names.rightcurv$file.names.rightcurv))

bmp(file="/data/chamal/projects/emilyO/Tissue_contrast/figures/paper/correct_sizing/curvature_intensity_acrosssubjects.bmp",width=3.25, height=3, units="in", res=300)
ggplot() + geom_jitter(mapping = aes(x = table.right_curv[1304,], y = table.right_int[1304,])) + labs(x = "Mean Curavture", y = "Tissue Intensity Ratio \n in Inferior Frontal Sulcus") +theme_bw(base_size = 10)
dev.off()
